/**
 * Shared option lists for form dropdowns/autocompletes across the app.
 * Use these for scientific field, field of interest, skills, etc. so labels stay consistent.
 */

/** Scientific fields / research interests. Used in post composer (scientific field) and profile (field of interest). */
export const SCIENCE_CATEGORIES = [
  "Acoustics",
  "Aerodynamics",
  "Anatomy",
  "Anthropology",
  "Archaeology",
  "Astronomy",
  "Astrophysics",
  "Biochemistry",
  "Biology",
  "Biophysics",
  "Biotechnology",
  "Botany",
  "Chemistry",
  "Climatology",
  "Cognitive Science",
  "Computer Science",
  "Data Science",
  "Ecology",
  "Economics",
  "Engineering",
  "Entomology",
  "Environmental Science",
  "Epidemiology",
  "General Sciences",
  "Genetics",
  "Geography",
  "Geology",
  "Geophysics",
  "Immunology",
  "Machine Learning",
  "Marine Biology",
  "Materials Science",
  "Mathematics",
  "Meteorology",
  "Microbiology",
  "Molecular Biology",
  "Neuroscience",
  "Oceanography",
  "Paleontology",
  "Pathology",
  "Pharmacology",
  "Physics",
  "Physiology",
  "Psychology",
  "Quantum Physics",
  "Robotics",
  "Seismology",
  "Sociology",
  "Statistics",
  "Toxicology",
  "Virology",
  "Zoology",
  "Other",
] as const;

/** Skills for profile. Shared so profile edit and any other skill selectors stay in sync. */
export const SKILL_OPTIONS = [
  "Data Analysis",
  "Lab Techniques",
  "Python",
  "R",
  "JavaScript",
  "C++",
  "Machine Learning",
  "Statistical Modeling",
  "Microbiology",
  "Molecular Biology",
  "Writing",
  "Presentation",
  "Grant Writing",
  "Other",
] as const;
