create extension if not exists "vector" with schema "extensions";

create type "public"."academia_role" as enum ('Postdoc', 'Faculty', 'PhD', 'Grad Student');

create type "public"."job_type" as enum ('Full-time', 'Part-time', 'Internship', 'Contract');

create type "public"."product_type_enum" as enum ('tool', 'platform', 'AI tool', 'simulation');

create type "public"."work_mode" as enum ('on-site', 'remote', 'hybrid');

create sequence "public"."products_product_id_seq";

create sequence "public"."publications_publication_id_seq";

create sequence "public"."tags_id_seq";

revoke update on table "public"."posts" from "authenticated";

  create table "public"."authors" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "openalex_author_id" text not null,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."authors_publications" (
    "id" uuid not null default gen_random_uuid(),
    "author_id" uuid not null,
    "publication_id" bigint not null
      );



  create table "public"."jobs" (
    "id" bigint generated by default as identity not null,
    "title" character varying not null default ''::character varying,
    "description" text not null default ''::text,
    "created_at" timestamp with time zone not null default now(),
    "poster_id" uuid not null,
    "summary" text,
    "location" text,
    "department" text,
    "organization" text,
    "work_mode" public.work_mode default 'on-site'::public.work_mode,
    "job_type" public.job_type,
    "academia_role" public.academia_role,
    "application_link" text
      );



  create table "public"."jobs_applicants" (
    "job_id" bigint not null,
    "user_id" uuid not null
      );



  create table "public"."jobs_skills" (
    "job_id" bigint not null,
    "skill_id" bigint not null,
    "is_required" boolean not null default false
      );



  create table "public"."jobs_tags" (
    "job_id" bigint not null,
    "tag_id" bigint not null
      );



  create table "public"."product_tags" (
    "product_id" bigint not null,
    "tag_id" bigint not null
      );



  create table "public"."products" (
    "product_id" bigint not null default nextval('public.products_product_id_seq'::regclass),
    "title" text not null,
    "short_summary" text,
    "website_link" text,
    "publication_id" bigint,
    "image_path" text,
    "github_link" text,
    "other_links" text[] default '{}'::text[],
    "contributors" text[] default '{}'::text[],
    "is_featured" boolean default false,
    "product_type" public.product_type_enum
      );



  create table "public"."profile_skills" (
    "profile_user_id" uuid not null,
    "skill_id" bigint not null
      );



  create table "public"."profile_tags" (
    "profile_user_id" uuid not null,
    "tag_id" bigint not null,
    "raw_count" integer,
    "weight" double precision
      );



  create table "public"."profile_tags_temp" (
    "profile_user_id" uuid,
    "tag_id" bigint,
    "raw_count" integer,
    "weight" double precision
      );



  create table "public"."publication_topics" (
    "publication_id" bigint not null,
    "topic_id" bigint not null
      );



  create table "public"."publications" (
    "publication_id" bigint not null default nextval('public.publications_publication_id_seq'::regclass),
    "title" text not null,
    "doi_link" text,
    "journal" text,
    "date_published" date,
    "authors" text[],
    "preview_path" text,
    "is_openalex" boolean default false
      );



  create table "public"."skills" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "embedding" extensions.vector not null
      );



  create table "public"."tags" (
    "id" bigint not null default nextval('public.tags_id_seq'::regclass),
    "name" text not null,
    "openalex_id" text,
    "level" integer,
    "parent_tag_id" integer,
    "description" text,
    "embedding" extensions.vector(1024),
    "keywords" text[]
      );



  create table "public"."user_products" (
    "user_id" uuid not null,
    "product_id" bigint not null
      );



  create table "public"."user_publications" (
    "user_id" uuid not null,
    "publication_id" bigint not null,
    "is_featured" boolean default false
      );


alter table "public"."group_members" alter column "group_id" add generated by default as identity;

alter table "public"."profile" add column "banner_pic_url" text;

alter table "public"."profile" add column "orcid" text;

alter table "public"."profile" add column "timezone" text;

alter sequence "public"."products_product_id_seq" owned by "public"."products"."product_id";

alter sequence "public"."publications_publication_id_seq" owned by "public"."publications"."publication_id";

alter sequence "public"."tags_id_seq" owned by "public"."tags"."id";

CREATE UNIQUE INDEX "Jobs_pkey" ON public.jobs USING btree (id);

CREATE UNIQUE INDEX authors_openalex_author_id_key ON public.authors USING btree (openalex_author_id);

CREATE UNIQUE INDEX authors_pkey ON public.authors USING btree (id);

CREATE UNIQUE INDEX authors_publications_author_id_publication_id_key ON public.authors_publications USING btree (author_id, publication_id);

CREATE UNIQUE INDEX authors_publications_pkey ON public.authors_publications USING btree (id);

CREATE INDEX idx_profile_tags_profile_user_id ON public.profile_tags USING btree (profile_user_id);

CREATE INDEX idx_profile_tags_tag_id ON public.profile_tags USING btree (tag_id);

CREATE UNIQUE INDEX jobs_applicants_pkey ON public.jobs_applicants USING btree (job_id, user_id);

CREATE UNIQUE INDEX jobs_skills_pkey ON public.jobs_skills USING btree (job_id, skill_id);

CREATE UNIQUE INDEX jobs_tags_pkey ON public.jobs_tags USING btree (job_id, tag_id);

CREATE UNIQUE INDEX product_tags_pkey ON public.product_tags USING btree (product_id, tag_id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (product_id);

CREATE UNIQUE INDEX profile_skills_pkey ON public.profile_skills USING btree (profile_user_id, skill_id);

CREATE UNIQUE INDEX profile_tags_pkey ON public.profile_tags USING btree (profile_user_id, tag_id);

CREATE UNIQUE INDEX publication_topics_pkey ON public.publication_topics USING btree (publication_id, topic_id);

CREATE UNIQUE INDEX publications_pkey ON public.publications USING btree (publication_id);

CREATE UNIQUE INDEX skills_id_key ON public.skills USING btree (id);

CREATE UNIQUE INDEX skills_name_key ON public.skills USING btree (name);

CREATE UNIQUE INDEX skills_pkey ON public.skills USING btree (id);

CREATE UNIQUE INDEX tags_openalex_id_unique ON public.tags USING btree (openalex_id);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

CREATE UNIQUE INDEX unique_openalex_id ON public.tags USING btree (openalex_id);

CREATE UNIQUE INDEX user_products_pkey ON public.user_products USING btree (user_id, product_id);

CREATE UNIQUE INDEX user_publications_pkey ON public.user_publications USING btree (user_id, publication_id);

alter table "public"."authors" add constraint "authors_pkey" PRIMARY KEY using index "authors_pkey";

alter table "public"."authors_publications" add constraint "authors_publications_pkey" PRIMARY KEY using index "authors_publications_pkey";

alter table "public"."jobs" add constraint "Jobs_pkey" PRIMARY KEY using index "Jobs_pkey";

alter table "public"."jobs_applicants" add constraint "jobs_applicants_pkey" PRIMARY KEY using index "jobs_applicants_pkey";

alter table "public"."jobs_skills" add constraint "jobs_skills_pkey" PRIMARY KEY using index "jobs_skills_pkey";

alter table "public"."jobs_tags" add constraint "jobs_tags_pkey" PRIMARY KEY using index "jobs_tags_pkey";

alter table "public"."product_tags" add constraint "product_tags_pkey" PRIMARY KEY using index "product_tags_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."profile_skills" add constraint "profile_skills_pkey" PRIMARY KEY using index "profile_skills_pkey";

alter table "public"."profile_tags" add constraint "profile_tags_pkey" PRIMARY KEY using index "profile_tags_pkey";

alter table "public"."publication_topics" add constraint "publication_topics_pkey" PRIMARY KEY using index "publication_topics_pkey";

alter table "public"."publications" add constraint "publications_pkey" PRIMARY KEY using index "publications_pkey";

alter table "public"."skills" add constraint "skills_pkey" PRIMARY KEY using index "skills_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."user_products" add constraint "user_products_pkey" PRIMARY KEY using index "user_products_pkey";

alter table "public"."user_publications" add constraint "user_publications_pkey" PRIMARY KEY using index "user_publications_pkey";

alter table "public"."authors" add constraint "authors_openalex_author_id_key" UNIQUE using index "authors_openalex_author_id_key";

alter table "public"."authors" add constraint "authors_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profile(user_id) ON DELETE SET NULL not valid;

alter table "public"."authors" validate constraint "authors_user_id_fkey";

alter table "public"."authors_publications" add constraint "authors_publications_author_id_fkey" FOREIGN KEY (author_id) REFERENCES public.authors(id) ON DELETE CASCADE not valid;

alter table "public"."authors_publications" validate constraint "authors_publications_author_id_fkey";

alter table "public"."authors_publications" add constraint "authors_publications_author_id_publication_id_key" UNIQUE using index "authors_publications_author_id_publication_id_key";

alter table "public"."authors_publications" add constraint "authors_publications_publication_id_fkey" FOREIGN KEY (publication_id) REFERENCES public.publications(publication_id) ON DELETE CASCADE not valid;

alter table "public"."authors_publications" validate constraint "authors_publications_publication_id_fkey";

alter table "public"."jobs" add constraint "jobs_poster_id_fkey" FOREIGN KEY (poster_id) REFERENCES public.profile(user_id) ON DELETE CASCADE not valid;

alter table "public"."jobs" validate constraint "jobs_poster_id_fkey";

alter table "public"."jobs_applicants" add constraint "jobs_applicants_job_id_fkey" FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE not valid;

alter table "public"."jobs_applicants" validate constraint "jobs_applicants_job_id_fkey";

alter table "public"."jobs_applicants" add constraint "jobs_applicants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profile(user_id) ON DELETE CASCADE not valid;

alter table "public"."jobs_applicants" validate constraint "jobs_applicants_user_id_fkey";

alter table "public"."jobs_skills" add constraint "jobs_skills_job_id_fkey" FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE not valid;

alter table "public"."jobs_skills" validate constraint "jobs_skills_job_id_fkey";

alter table "public"."jobs_skills" add constraint "jobs_skills_job_id_fkey1" FOREIGN KEY (job_id) REFERENCES public.skills(id) ON DELETE CASCADE not valid;

alter table "public"."jobs_skills" validate constraint "jobs_skills_job_id_fkey1";

alter table "public"."jobs_tags" add constraint "jobs_tags_job_id_fkey" FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE not valid;

alter table "public"."jobs_tags" validate constraint "jobs_tags_job_id_fkey";

alter table "public"."jobs_tags" add constraint "jobs_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE not valid;

alter table "public"."jobs_tags" validate constraint "jobs_tags_tag_id_fkey";

alter table "public"."product_tags" add constraint "product_tags_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON DELETE CASCADE not valid;

alter table "public"."product_tags" validate constraint "product_tags_product_id_fkey";

alter table "public"."product_tags" add constraint "product_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE not valid;

alter table "public"."product_tags" validate constraint "product_tags_tag_id_fkey";

alter table "public"."products" add constraint "products_other_links_check" CHECK ((array_length(other_links, 1) <= 3)) not valid;

alter table "public"."products" validate constraint "products_other_links_check";

alter table "public"."products" add constraint "products_publication_id_fkey" FOREIGN KEY (publication_id) REFERENCES public.publications(publication_id) ON DELETE SET NULL not valid;

alter table "public"."products" validate constraint "products_publication_id_fkey";

alter table "public"."profile_skills" add constraint "profile_skills_profile_user_id_fkey" FOREIGN KEY (profile_user_id) REFERENCES public.profile(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile_skills" validate constraint "profile_skills_profile_user_id_fkey";

alter table "public"."profile_skills" add constraint "profile_skills_skill_id_fkey" FOREIGN KEY (skill_id) REFERENCES public.skills(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile_skills" validate constraint "profile_skills_skill_id_fkey";

alter table "public"."profile_tags" add constraint "profile_tags_profile_user_id_fkey" FOREIGN KEY (profile_user_id) REFERENCES public.profile(user_id) ON DELETE CASCADE not valid;

alter table "public"."profile_tags" validate constraint "profile_tags_profile_user_id_fkey";

alter table "public"."profile_tags" add constraint "profile_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE not valid;

alter table "public"."profile_tags" validate constraint "profile_tags_tag_id_fkey";

alter table "public"."publication_topics" add constraint "publication_topics_publication_id_fkey" FOREIGN KEY (publication_id) REFERENCES public.publications(publication_id) ON DELETE CASCADE not valid;

alter table "public"."publication_topics" validate constraint "publication_topics_publication_id_fkey";

alter table "public"."publication_topics" add constraint "publication_topics_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES public.tags(id) ON DELETE CASCADE not valid;

alter table "public"."publication_topics" validate constraint "publication_topics_topic_id_fkey";

alter table "public"."skills" add constraint "skills_id_key" UNIQUE using index "skills_id_key";

alter table "public"."skills" add constraint "skills_name_key" UNIQUE using index "skills_name_key";

alter table "public"."tags" add constraint "tags_parent_tag_id_fkey" FOREIGN KEY (parent_tag_id) REFERENCES public.tags(id) not valid;

alter table "public"."tags" validate constraint "tags_parent_tag_id_fkey";

alter table "public"."tags" add constraint "unique_openalex_id" UNIQUE using index "unique_openalex_id";

alter table "public"."user_products" add constraint "user_products_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON DELETE CASCADE not valid;

alter table "public"."user_products" validate constraint "user_products_product_id_fkey";

alter table "public"."user_products" add constraint "user_products_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profile(user_id) ON DELETE CASCADE not valid;

alter table "public"."user_products" validate constraint "user_products_user_id_fkey";

alter table "public"."user_publications" add constraint "user_publications_publication_id_fkey" FOREIGN KEY (publication_id) REFERENCES public.publications(publication_id) ON DELETE CASCADE not valid;

alter table "public"."user_publications" validate constraint "user_publications_publication_id_fkey";

alter table "public"."user_publications" add constraint "user_publications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profile(user_id) ON DELETE CASCADE not valid;

alter table "public"."user_publications" validate constraint "user_publications_user_id_fkey";

alter table "public"."follows" validate constraint "follows_following_id_fkey";

alter table "public"."messages" validate constraint "messages_sender_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_collaborators(current_user_id uuid)
 RETURNS TABLE(profile_user_id uuid, cosine_similarity double precision, first_name text, last_name text, profile_pic_path text, occupation text, workplace text)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
  RETURN QUERY
  WITH overlap AS (
    SELECT pt2.profile_user_id,
      SUM(pt1.weight * pt2.weight) AS dot_product
    FROM profile_tags pt1
    JOIN profile_tags pt2 ON pt1.tag_id = pt2.tag_id
    WHERE pt1.profile_user_id = current_user_id
      AND pt2.profile_user_id != current_user_id
    GROUP BY pt2.profile_user_id
  ),
  magnitudes AS (
    SELECT pt.profile_user_id,
      SQRT(SUM(pt.weight * pt.weight)) AS magnitude
    FROM profile_tags pt
    GROUP BY pt.profile_user_id
  )
  SELECT o.profile_user_id,
    o.dot_product / (m1.magnitude * m2.magnitude) AS cosine_similarity,
    p.first_name,
    p.last_name,
    p.header_pic_path,
    p.occupation,
    p.workplace
  FROM overlap o
  JOIN magnitudes m1 ON m1.profile_user_id = current_user_id
  JOIN magnitudes m2 ON m2.profile_user_id = o.profile_user_id
  JOIN profile p ON p.user_id = o.profile_user_id
  ORDER BY cosine_similarity DESC;
END;$function$
;

CREATE OR REPLACE FUNCTION public.scale_vector(v extensions.vector, s double precision)
 RETURNS extensions.vector
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN (SELECT array_agg(x * s)::vector FROM unnest(v::float4[]) AS x);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.accept_group_invite(target_group_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  current_user_id uuid := auth.uid();
  target_conversation_id bigint;
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.invites i
    WHERE i.group_id = target_group_id
      AND i.user_id = current_user_id
      AND (i.status = 'pending' OR i.status IS NULL)
  ) THEN
    RAISE EXCEPTION 'No pending invitation for this group';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.group_members gm
    WHERE gm.group_id = target_group_id
      AND gm.user_id = current_user_id
  ) THEN
    UPDATE public.invites
    SET status = 'accepted'
    WHERE group_id = target_group_id
      AND user_id = current_user_id;
    RETURN;
  END IF;

  INSERT INTO public.group_members (group_id, user_id, role)
  VALUES (target_group_id, current_user_id, 'Member');

  SELECT g.conversation_id
  INTO target_conversation_id
  FROM public.groups g
  WHERE g.group_id = target_group_id;

  IF target_conversation_id IS NOT NULL THEN
    INSERT INTO public.conversation_participants (conversation_id, user_id)
    VALUES (target_conversation_id, current_user_id)
    ON CONFLICT DO NOTHING;
  END IF;

  UPDATE public.invites
  SET status = 'accepted'
  WHERE group_id = target_group_id
    AND user_id = current_user_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.add_group_member(target_group_id bigint, target_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM group_members
    WHERE group_id = target_group_id AND user_id = auth.uid() AND role = 'Admin'
  ) THEN RAISE EXCEPTION 'Not authorized';
  END IF;

  INSERT INTO group_members (group_id, user_id, role)
  VALUES (target_group_id, target_user_id, 'Member');

  INSERT INTO conversation_participants (conversation_id, user_id)
  SELECT g.conversation_id, target_user_id
  FROM groups g WHERE g.group_id = target_group_id AND g.conversation_id IS NOT NULL
  ON CONFLICT DO NOTHING;
END;
$function$
;

drop view if exists "public"."chat_sidebar";

create or replace view "public"."chat_sidebar" as  SELECT c.id AS conversation_id,
    c.name,
    c.is_group,
    m.id AS message_id,
    m.sender_id,
    m.content AS last_message,
    m.created_at AS last_message_at
   FROM ((public.conversations c
     JOIN public.conversation_participants cp ON ((c.id = cp.conversation_id)))
     LEFT JOIN LATERAL ( SELECT messages.id,
            messages.sender_id,
            messages.content,
            messages.created_at
           FROM public.messages
          WHERE (messages.conversation_id = c.id)
          ORDER BY messages.created_at DESC
         LIMIT 1) m ON (true))
  WHERE (cp.user_id = auth.uid());


CREATE OR REPLACE FUNCTION public.create_conversation(participant_ids uuid[])
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  new_conversation_id bigint;
  p_id uuid;
begin
  -- 1. Create the container
  insert into public.conversations (is_group)
  values (false) -- defaulting to DM for now
  returning id into new_conversation_id;

  -- 2. Add all participants (Loop through the array)
  foreach p_id in array participant_ids
  loop
    insert into public.conversation_participants (conversation_id, user_id)
    values (new_conversation_id, p_id);
  end loop;

  -- 3. Return the ID so the frontend can redirect the user
  return new_conversation_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_group(group_name text, group_description text, creator_id uuid)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  new_group_id bigint;
  new_conversation_id bigint;
BEGIN
  INSERT INTO conversations (is_group, name)
  VALUES (true, group_name)
  RETURNING id INTO new_conversation_id;

  INSERT INTO conversation_participants (conversation_id, user_id)
  VALUES (new_conversation_id, creator_id);

  INSERT INTO groups (name, description, conversation_id)
  VALUES (group_name, group_description, new_conversation_id)
  RETURNING group_id INTO new_group_id;

  INSERT INTO group_members (group_id, user_id, role)
  VALUES (new_group_id, creator_id, 'Admin');

  RETURN new_group_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_group(p_name text, p_description text, p_privacy text DEFAULT 'public'::text, p_topics text[] DEFAULT '{}'::text[], p_rules text DEFAULT ''::text)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  new_group_id bigint;
  new_conversation_id bigint;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'You must be logged in to create a group';
  END IF;

  INSERT INTO public.conversations (is_group, name)
  VALUES (true, p_name)
  RETURNING id INTO new_conversation_id;

  INSERT INTO public.conversation_participants (conversation_id, user_id)
  VALUES (new_conversation_id, auth.uid());

  INSERT INTO public.groups (name, description, conversation_id, privacy, topics, rules)
  VALUES (p_name, p_description, new_conversation_id, p_privacy, p_topics, p_rules)
  RETURNING group_id INTO new_group_id;

  INSERT INTO public.group_members (group_id, user_id, role)
  VALUES (new_group_id, auth.uid(), 'Admin');

  RETURN new_group_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_group(target_group_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  conv_id bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM group_members
    WHERE group_id = target_group_id AND user_id = auth.uid() AND role = 'Admin'
  ) THEN RAISE EXCEPTION 'Not authorized';
  END IF;

  SELECT conversation_id INTO conv_id FROM groups WHERE group_id = target_group_id;

  DELETE FROM comment_likes WHERE comment_id IN (
    SELECT comment_id FROM comment WHERE post_id IN (SELECT post_id FROM posts WHERE group_id = target_group_id)
  );
  DELETE FROM feed_report WHERE post_id IN (SELECT post_id FROM posts WHERE group_id = target_group_id);
  DELETE FROM comment WHERE post_id IN (SELECT post_id FROM posts WHERE group_id = target_group_id);
  DELETE FROM likes WHERE post_id IN (SELECT post_id FROM posts WHERE group_id = target_group_id);
  DELETE FROM posts WHERE group_id = target_group_id;

  DELETE FROM invites WHERE group_id = target_group_id;
  DELETE FROM group_members WHERE group_id = target_group_id;

  DELETE FROM groups WHERE group_id = target_group_id;

  IF conv_id IS NOT NULL THEN
    DELETE FROM messages WHERE conversation_id = conv_id;
    DELETE FROM conversation_participants WHERE conversation_id = conv_id;
    DELETE FROM conversations WHERE id = conv_id;
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_group_invite()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  wants_notification boolean;
BEGIN
  SELECT is_enabled INTO wants_notification FROM public.notification_preferences
  WHERE user_id = NEW.user_id AND notification_type = 'group_invite';

  IF wants_notification = false THEN RETURN NEW; END IF;

  INSERT INTO public.notifications (user_id, type, title, content, link)
  VALUES (NEW.user_id, 'group_invite', 'Group Invitation', 'You have been invited to a group.', '/groups/' || NEW.group_id);

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  -- Create users row
  insert into public.users (
    user_id,
    email,
    first_name,
    last_name
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', '')
  )
  on conflict (user_id) do nothing;

  -- Create profile row
  insert into public.profile (
    user_id,
    first_name,
    last_name
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', '')
  )
  on conflict (user_id) do nothing;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_comment()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  target_user_id uuid;
  wants_notification boolean;
  is_item_muted boolean; -- 1. We declare our new variable
BEGIN
  -- Find the author of the post
  SELECT user_id INTO target_user_id FROM public.posts WHERE post_id = NEW.post_id;
  
  -- Don't notify the user if they commented on their own post
  IF target_user_id = NEW.user_id THEN RETURN NEW; END IF;

  -- 2. NEW LOGIC: Check if the specific post is muted
  SELECT EXISTS (
    SELECT 1 FROM public.muted_items 
    WHERE user_id = target_user_id AND item_id = NEW.post_id AND item_type = 'post'
  ) INTO is_item_muted;

  -- If the post is muted, exit immediately!
  IF is_item_muted = true THEN RETURN NEW; END IF;

  -- Check global preferences (the logic we wrote previously)
  SELECT is_enabled INTO wants_notification FROM public.notification_preferences 
  WHERE user_id = target_user_id AND notification_type = 'new_comment';
  
  IF wants_notification = false THEN RETURN NEW; END IF;

  -- If we passed all checks, create the notification!
  INSERT INTO public.notifications (user_id, type, title, content, link)
  VALUES (target_user_id, 'new_comment', 'New Comment!', 'Someone commented on your post.', '/posts/' || NEW.post_id);
  
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_follow()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  wants_notification boolean;
BEGIN
  SELECT is_enabled INTO wants_notification FROM public.notification_preferences 
  WHERE user_id = NEW.following_id AND notification_type = 'new_follow';
  
  IF wants_notification = false THEN RETURN NEW; END IF;

  INSERT INTO public.notifications (user_id, type, title, content, link)
  VALUES (NEW.following_id, 'new_follow', 'New Follower!', 'Someone started following you.', '/profile/' || NEW.follower_id);
  
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_like()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  target_user_id uuid;
  wants_notification boolean;
  is_item_muted boolean; -- Our new variable
BEGIN
  -- Find the author of the post
  SELECT user_id INTO target_user_id FROM public.posts WHERE post_id = NEW.post_id;
  
  -- Don't notify the user if they liked their own post
  IF target_user_id = NEW.user_id THEN RETURN NEW; END IF;

  -- NEW LOGIC: Check if the specific post is muted
  SELECT EXISTS (
    SELECT 1 FROM public.muted_items 
    WHERE user_id = target_user_id AND item_id = NEW.post_id AND item_type = 'post'
  ) INTO is_item_muted;

  -- If the post is muted, exit immediately
  IF is_item_muted = true THEN RETURN NEW; END IF;

  -- Check global preferences
  SELECT is_enabled INTO wants_notification FROM public.notification_preferences 
  WHERE user_id = target_user_id AND notification_type = 'post_like';
  
  IF wants_notification = false THEN RETURN NEW; END IF;

  -- Create Notification
  INSERT INTO public.notifications (user_id, type, title, content, link)
  VALUES (target_user_id, 'post_like', 'New Like!', 'Someone liked your post.', '/posts/' || NEW.post_id);
  
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_message()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Insert notifications for all participants except the sender, 
  -- checking both global preferences AND specific muted conversations
  INSERT INTO public.notifications (user_id, type, title, content, link)
  SELECT 
    cp.user_id, 
    'new_message', 
    'New Message', 
    'You received a new message.', 
    '/chat/' || NEW.conversation_id
  FROM public.conversation_participants cp
  LEFT JOIN public.notification_preferences np 
    ON np.user_id = cp.user_id AND np.notification_type = 'new_message'
  WHERE cp.conversation_id = NEW.conversation_id 
    AND cp.user_id != NEW.sender_id
    AND (np.is_enabled IS NULL OR np.is_enabled = true)
    -- NEW LOGIC: Exclude users who have this specific conversation muted
    AND NOT EXISTS (
      SELECT 1 FROM public.muted_items mi 
      WHERE mi.user_id = cp.user_id 
        AND mi.item_id = NEW.conversation_id 
        AND mi.item_type = 'conversation'
    );
  
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.invite_user_to_group(p_group_id bigint, p_target_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.group_members
    WHERE group_id = p_group_id AND user_id = auth.uid() AND role = 'Admin'
  ) THEN
    RAISE EXCEPTION 'Not authorized to invite members to this group';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.group_members
    WHERE group_id = p_group_id AND user_id = p_target_user_id
  ) THEN
    RAISE EXCEPTION 'User is already a member of this group';
  END IF;

  INSERT INTO public.invites (group_id, user_id, status)
  VALUES (p_group_id, p_target_user_id, 'pending');
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_group_member(gid bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM group_members
    WHERE group_id = gid AND user_id = auth.uid()
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_participant(_conversation_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN EXISTS (
    SELECT 1 
    FROM public.conversation_participants 
    WHERE conversation_id = _conversation_id -- No more ambiguity!
    AND user_id = auth.uid()
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.join_public_group(target_group_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF EXISTS (SELECT 1 FROM public.group_bans WHERE group_id = target_group_id AND user_id = auth.uid()) THEN
    RAISE EXCEPTION 'You are banned from this group';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.groups WHERE group_id = target_group_id AND privacy = 'public') THEN
    RAISE EXCEPTION 'Group is private or does not exist';
  END IF;

  IF EXISTS (SELECT 1 FROM public.group_members WHERE group_id = target_group_id AND user_id = auth.uid()) THEN
    RAISE EXCEPTION 'You are already a member of this group';
  END IF;

  INSERT INTO public.group_members (group_id, user_id, role)
  VALUES (target_group_id, auth.uid(), 'Member');

  INSERT INTO public.conversation_participants (conversation_id, user_id)
  SELECT conversation_id, auth.uid()
  FROM public.groups
  WHERE group_id = target_group_id AND conversation_id IS NOT NULL
  ON CONFLICT DO NOTHING;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.remove_group_member(target_group_id bigint, target_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM group_members
    WHERE group_id = target_group_id AND user_id = auth.uid() AND role = 'Admin'
  ) THEN RAISE EXCEPTION 'Not authorized';
  END IF;

  IF EXISTS (
    SELECT 1 FROM group_members
    WHERE group_id = target_group_id AND user_id = target_user_id AND role = 'Admin'
  ) THEN RAISE EXCEPTION 'Cannot remove an Admin';
  END IF;

  DELETE FROM group_members
  WHERE group_id = target_group_id AND user_id = target_user_id;

  DELETE FROM conversation_participants
  WHERE user_id = target_user_id
    AND conversation_id = (SELECT conversation_id FROM groups WHERE group_id = target_group_id);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.search_all_content(search_query text)
 RETURNS SETOF public.user_generated_content_search
 LANGUAGE plpgsql
AS $function$
BEGIN
  SET LOCAL pg_trgm.similarity_threshold = 0.15;

  RETURN QUERY
  SELECT *
  FROM public.user_generated_content_search
  WHERE 
    tsv @@ websearch_to_tsquery('english', search_query)
    OR names % search_query
    OR category % search_query
    OR names ILIKE '%' || search_query || '%'
    OR category ILIKE '%' || search_query || '%'
  ORDER BY 
    GREATEST(
      ts_rank(tsv, websearch_to_tsquery('english', search_query)),
      similarity(names, search_query),
      similarity(category, search_query)
    ) DESC
  LIMIT 50;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.search_groups(search_query text)
 RETURNS SETOF public.groups
 LANGUAGE plpgsql
AS $function$
BEGIN
  SET LOCAL pg_trgm.similarity_threshold = 0.15;

  RETURN QUERY
  SELECT *
  FROM public.groups
  WHERE
    to_tsvector('english', concat_ws(' ', name, description, array_to_string(topics, ' '), rules))
    @@ websearch_to_tsquery('english', search_query)
    OR
    name % search_query
  ORDER BY
    GREATEST(
      ts_rank(
        to_tsvector('english', concat_ws(' ', name, description, array_to_string(topics, ' '), rules)),
        websearch_to_tsquery('english', search_query)
      ),
      similarity(name, search_query)
    ) DESC
  LIMIT 50;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.search_posts(search_query text)
 RETURNS SETOF public.posts
 LANGUAGE plpgsql
AS $function$
BEGIN
  SET LOCAL pg_trgm.similarity_threshold = 0.15;

  RETURN QUERY
  SELECT *
  FROM public.posts
  WHERE 
    to_tsvector('english', concat_ws(' ', text, category, scientific_field)) 
    @@ websearch_to_tsquery('english', search_query)
    OR 
    concat_ws(' ', text, category, scientific_field) % search_query
  ORDER BY 
    GREATEST(
      ts_rank(
        to_tsvector('english', concat_ws(' ', text, category, scientific_field)),
        websearch_to_tsquery('english', search_query)
      ),
      similarity(concat_ws(' ', text, category, scientific_field), search_query)
    ) DESC
  LIMIT 50;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.search_users(search_query text)
 RETURNS TABLE(user_id uuid, first_name text, last_name text, email text, profile_pic_path text, profession text, occupation text, workplace text, about text, skill text[])
 LANGUAGE plpgsql
AS $function$
BEGIN
  SET LOCAL pg_trgm.similarity_threshold = 0.15;

  RETURN QUERY
  SELECT u.user_id, u.first_name, u.last_name, u.email, u.profile_pic_path,
         p.profession, p.occupation, p.workplace, p.about, p.skill
  FROM public.users u
  LEFT JOIN public.profile p ON u.user_id = p.user_id
  WHERE 
    to_tsvector('english', concat_ws(' ', u.first_name, u.last_name, u.email, p.profession, p.about, array_to_string(p.skill, ' '), p.occupation, p.workplace)) 
    @@ websearch_to_tsquery('english', search_query)
    OR 
    concat_ws(' ', u.first_name, u.last_name) % search_query
    OR 
    concat_ws(' ', u.first_name, u.last_name) ILIKE '%' || search_query || '%'
  ORDER BY 
    GREATEST(
      ts_rank(
        to_tsvector('english', concat_ws(' ', u.first_name, u.last_name, u.email, p.profession, p.about, array_to_string(p.skill, ' '), p.occupation, p.workplace)),
        websearch_to_tsquery('english', search_query)
      ),
      similarity(concat_ws(' ', u.first_name, u.last_name), search_query)
    ) DESC
  LIMIT 50;
END;
$function$
;

create or replace view "public"."user_generated_content_search" as  SELECT 'post'::text AS content_type,
    p.text AS content,
    p.category,
    (p.post_id)::text AS id,
    concat_ws(' '::text, u.first_name, u.last_name) AS names,
    to_tsvector('english'::regconfig, concat_ws(' '::text, p.text, p.category, u.first_name, u.last_name)) AS tsv
   FROM (public.users u
     JOIN public.posts p ON ((p.user_id = u.user_id)))
UNION ALL
 SELECT 'article'::text AS content_type,
    articles.article_link AS content,
    articles.source AS category,
    (articles.article_id)::text AS id,
    articles.researchers AS names,
    to_tsvector('english'::regconfig, concat_ws(' '::text, articles.source, articles.researchers)) AS tsv
   FROM public.articles
UNION ALL
 SELECT 'group'::text AS content_type,
    groups.description AS content,
    'user-defined group'::text AS category,
    (groups.group_id)::text AS id,
    groups.name AS names,
    to_tsvector('english'::regconfig, concat_ws(' '::text, groups.description, groups.name)) AS tsv
   FROM public.groups
UNION ALL
 SELECT 'user'::text AS content_type,
    users.email AS content,
    'User Profile'::text AS category,
    (users.user_id)::text AS id,
    concat_ws(' '::text, users.first_name, users.last_name) AS names,
    to_tsvector('english'::regconfig, concat_ws(' '::text, users.first_name, users.last_name, users.email)) AS tsv
   FROM public.users;


grant delete on table "public"."authors" to "anon";

grant insert on table "public"."authors" to "anon";

grant references on table "public"."authors" to "anon";

grant select on table "public"."authors" to "anon";

grant trigger on table "public"."authors" to "anon";

grant truncate on table "public"."authors" to "anon";

grant update on table "public"."authors" to "anon";

grant delete on table "public"."authors" to "authenticated";

grant insert on table "public"."authors" to "authenticated";

grant references on table "public"."authors" to "authenticated";

grant select on table "public"."authors" to "authenticated";

grant trigger on table "public"."authors" to "authenticated";

grant truncate on table "public"."authors" to "authenticated";

grant update on table "public"."authors" to "authenticated";

grant delete on table "public"."authors" to "service_role";

grant insert on table "public"."authors" to "service_role";

grant references on table "public"."authors" to "service_role";

grant select on table "public"."authors" to "service_role";

grant trigger on table "public"."authors" to "service_role";

grant truncate on table "public"."authors" to "service_role";

grant update on table "public"."authors" to "service_role";

grant delete on table "public"."authors_publications" to "anon";

grant insert on table "public"."authors_publications" to "anon";

grant references on table "public"."authors_publications" to "anon";

grant select on table "public"."authors_publications" to "anon";

grant trigger on table "public"."authors_publications" to "anon";

grant truncate on table "public"."authors_publications" to "anon";

grant update on table "public"."authors_publications" to "anon";

grant delete on table "public"."authors_publications" to "authenticated";

grant insert on table "public"."authors_publications" to "authenticated";

grant references on table "public"."authors_publications" to "authenticated";

grant select on table "public"."authors_publications" to "authenticated";

grant trigger on table "public"."authors_publications" to "authenticated";

grant truncate on table "public"."authors_publications" to "authenticated";

grant update on table "public"."authors_publications" to "authenticated";

grant delete on table "public"."authors_publications" to "service_role";

grant insert on table "public"."authors_publications" to "service_role";

grant references on table "public"."authors_publications" to "service_role";

grant select on table "public"."authors_publications" to "service_role";

grant trigger on table "public"."authors_publications" to "service_role";

grant truncate on table "public"."authors_publications" to "service_role";

grant update on table "public"."authors_publications" to "service_role";

grant delete on table "public"."jobs" to "anon";

grant insert on table "public"."jobs" to "anon";

grant references on table "public"."jobs" to "anon";

grant select on table "public"."jobs" to "anon";

grant trigger on table "public"."jobs" to "anon";

grant truncate on table "public"."jobs" to "anon";

grant update on table "public"."jobs" to "anon";

grant delete on table "public"."jobs" to "authenticated";

grant insert on table "public"."jobs" to "authenticated";

grant references on table "public"."jobs" to "authenticated";

grant select on table "public"."jobs" to "authenticated";

grant trigger on table "public"."jobs" to "authenticated";

grant truncate on table "public"."jobs" to "authenticated";

grant update on table "public"."jobs" to "authenticated";

grant delete on table "public"."jobs" to "service_role";

grant insert on table "public"."jobs" to "service_role";

grant references on table "public"."jobs" to "service_role";

grant select on table "public"."jobs" to "service_role";

grant trigger on table "public"."jobs" to "service_role";

grant truncate on table "public"."jobs" to "service_role";

grant update on table "public"."jobs" to "service_role";

grant delete on table "public"."jobs_applicants" to "anon";

grant insert on table "public"."jobs_applicants" to "anon";

grant references on table "public"."jobs_applicants" to "anon";

grant select on table "public"."jobs_applicants" to "anon";

grant trigger on table "public"."jobs_applicants" to "anon";

grant truncate on table "public"."jobs_applicants" to "anon";

grant update on table "public"."jobs_applicants" to "anon";

grant delete on table "public"."jobs_applicants" to "authenticated";

grant insert on table "public"."jobs_applicants" to "authenticated";

grant references on table "public"."jobs_applicants" to "authenticated";

grant select on table "public"."jobs_applicants" to "authenticated";

grant trigger on table "public"."jobs_applicants" to "authenticated";

grant truncate on table "public"."jobs_applicants" to "authenticated";

grant update on table "public"."jobs_applicants" to "authenticated";

grant delete on table "public"."jobs_applicants" to "service_role";

grant insert on table "public"."jobs_applicants" to "service_role";

grant references on table "public"."jobs_applicants" to "service_role";

grant select on table "public"."jobs_applicants" to "service_role";

grant trigger on table "public"."jobs_applicants" to "service_role";

grant truncate on table "public"."jobs_applicants" to "service_role";

grant update on table "public"."jobs_applicants" to "service_role";

grant delete on table "public"."jobs_skills" to "anon";

grant insert on table "public"."jobs_skills" to "anon";

grant references on table "public"."jobs_skills" to "anon";

grant select on table "public"."jobs_skills" to "anon";

grant trigger on table "public"."jobs_skills" to "anon";

grant truncate on table "public"."jobs_skills" to "anon";

grant update on table "public"."jobs_skills" to "anon";

grant delete on table "public"."jobs_skills" to "authenticated";

grant insert on table "public"."jobs_skills" to "authenticated";

grant references on table "public"."jobs_skills" to "authenticated";

grant select on table "public"."jobs_skills" to "authenticated";

grant trigger on table "public"."jobs_skills" to "authenticated";

grant truncate on table "public"."jobs_skills" to "authenticated";

grant update on table "public"."jobs_skills" to "authenticated";

grant delete on table "public"."jobs_skills" to "service_role";

grant insert on table "public"."jobs_skills" to "service_role";

grant references on table "public"."jobs_skills" to "service_role";

grant select on table "public"."jobs_skills" to "service_role";

grant trigger on table "public"."jobs_skills" to "service_role";

grant truncate on table "public"."jobs_skills" to "service_role";

grant update on table "public"."jobs_skills" to "service_role";

grant delete on table "public"."jobs_tags" to "anon";

grant insert on table "public"."jobs_tags" to "anon";

grant references on table "public"."jobs_tags" to "anon";

grant select on table "public"."jobs_tags" to "anon";

grant trigger on table "public"."jobs_tags" to "anon";

grant truncate on table "public"."jobs_tags" to "anon";

grant update on table "public"."jobs_tags" to "anon";

grant delete on table "public"."jobs_tags" to "authenticated";

grant insert on table "public"."jobs_tags" to "authenticated";

grant references on table "public"."jobs_tags" to "authenticated";

grant select on table "public"."jobs_tags" to "authenticated";

grant trigger on table "public"."jobs_tags" to "authenticated";

grant truncate on table "public"."jobs_tags" to "authenticated";

grant update on table "public"."jobs_tags" to "authenticated";

grant delete on table "public"."jobs_tags" to "service_role";

grant insert on table "public"."jobs_tags" to "service_role";

grant references on table "public"."jobs_tags" to "service_role";

grant select on table "public"."jobs_tags" to "service_role";

grant trigger on table "public"."jobs_tags" to "service_role";

grant truncate on table "public"."jobs_tags" to "service_role";

grant update on table "public"."jobs_tags" to "service_role";

grant delete on table "public"."product_tags" to "anon";

grant insert on table "public"."product_tags" to "anon";

grant references on table "public"."product_tags" to "anon";

grant select on table "public"."product_tags" to "anon";

grant trigger on table "public"."product_tags" to "anon";

grant truncate on table "public"."product_tags" to "anon";

grant update on table "public"."product_tags" to "anon";

grant delete on table "public"."product_tags" to "authenticated";

grant insert on table "public"."product_tags" to "authenticated";

grant references on table "public"."product_tags" to "authenticated";

grant select on table "public"."product_tags" to "authenticated";

grant trigger on table "public"."product_tags" to "authenticated";

grant truncate on table "public"."product_tags" to "authenticated";

grant update on table "public"."product_tags" to "authenticated";

grant delete on table "public"."product_tags" to "service_role";

grant insert on table "public"."product_tags" to "service_role";

grant references on table "public"."product_tags" to "service_role";

grant select on table "public"."product_tags" to "service_role";

grant trigger on table "public"."product_tags" to "service_role";

grant truncate on table "public"."product_tags" to "service_role";

grant update on table "public"."product_tags" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."profile_skills" to "anon";

grant insert on table "public"."profile_skills" to "anon";

grant references on table "public"."profile_skills" to "anon";

grant select on table "public"."profile_skills" to "anon";

grant trigger on table "public"."profile_skills" to "anon";

grant truncate on table "public"."profile_skills" to "anon";

grant update on table "public"."profile_skills" to "anon";

grant delete on table "public"."profile_skills" to "authenticated";

grant insert on table "public"."profile_skills" to "authenticated";

grant references on table "public"."profile_skills" to "authenticated";

grant select on table "public"."profile_skills" to "authenticated";

grant trigger on table "public"."profile_skills" to "authenticated";

grant truncate on table "public"."profile_skills" to "authenticated";

grant update on table "public"."profile_skills" to "authenticated";

grant delete on table "public"."profile_skills" to "service_role";

grant insert on table "public"."profile_skills" to "service_role";

grant references on table "public"."profile_skills" to "service_role";

grant select on table "public"."profile_skills" to "service_role";

grant trigger on table "public"."profile_skills" to "service_role";

grant truncate on table "public"."profile_skills" to "service_role";

grant update on table "public"."profile_skills" to "service_role";

grant delete on table "public"."profile_tags" to "anon";

grant insert on table "public"."profile_tags" to "anon";

grant references on table "public"."profile_tags" to "anon";

grant select on table "public"."profile_tags" to "anon";

grant trigger on table "public"."profile_tags" to "anon";

grant truncate on table "public"."profile_tags" to "anon";

grant update on table "public"."profile_tags" to "anon";

grant delete on table "public"."profile_tags" to "authenticated";

grant insert on table "public"."profile_tags" to "authenticated";

grant references on table "public"."profile_tags" to "authenticated";

grant select on table "public"."profile_tags" to "authenticated";

grant trigger on table "public"."profile_tags" to "authenticated";

grant truncate on table "public"."profile_tags" to "authenticated";

grant update on table "public"."profile_tags" to "authenticated";

grant delete on table "public"."profile_tags" to "service_role";

grant insert on table "public"."profile_tags" to "service_role";

grant references on table "public"."profile_tags" to "service_role";

grant select on table "public"."profile_tags" to "service_role";

grant trigger on table "public"."profile_tags" to "service_role";

grant truncate on table "public"."profile_tags" to "service_role";

grant update on table "public"."profile_tags" to "service_role";

grant delete on table "public"."profile_tags_temp" to "anon";

grant insert on table "public"."profile_tags_temp" to "anon";

grant references on table "public"."profile_tags_temp" to "anon";

grant select on table "public"."profile_tags_temp" to "anon";

grant trigger on table "public"."profile_tags_temp" to "anon";

grant truncate on table "public"."profile_tags_temp" to "anon";

grant update on table "public"."profile_tags_temp" to "anon";

grant delete on table "public"."profile_tags_temp" to "authenticated";

grant insert on table "public"."profile_tags_temp" to "authenticated";

grant references on table "public"."profile_tags_temp" to "authenticated";

grant select on table "public"."profile_tags_temp" to "authenticated";

grant trigger on table "public"."profile_tags_temp" to "authenticated";

grant truncate on table "public"."profile_tags_temp" to "authenticated";

grant update on table "public"."profile_tags_temp" to "authenticated";

grant delete on table "public"."profile_tags_temp" to "service_role";

grant insert on table "public"."profile_tags_temp" to "service_role";

grant references on table "public"."profile_tags_temp" to "service_role";

grant select on table "public"."profile_tags_temp" to "service_role";

grant trigger on table "public"."profile_tags_temp" to "service_role";

grant truncate on table "public"."profile_tags_temp" to "service_role";

grant update on table "public"."profile_tags_temp" to "service_role";

grant delete on table "public"."publication_topics" to "anon";

grant insert on table "public"."publication_topics" to "anon";

grant references on table "public"."publication_topics" to "anon";

grant select on table "public"."publication_topics" to "anon";

grant trigger on table "public"."publication_topics" to "anon";

grant truncate on table "public"."publication_topics" to "anon";

grant update on table "public"."publication_topics" to "anon";

grant delete on table "public"."publication_topics" to "authenticated";

grant insert on table "public"."publication_topics" to "authenticated";

grant references on table "public"."publication_topics" to "authenticated";

grant select on table "public"."publication_topics" to "authenticated";

grant trigger on table "public"."publication_topics" to "authenticated";

grant truncate on table "public"."publication_topics" to "authenticated";

grant update on table "public"."publication_topics" to "authenticated";

grant delete on table "public"."publication_topics" to "service_role";

grant insert on table "public"."publication_topics" to "service_role";

grant references on table "public"."publication_topics" to "service_role";

grant select on table "public"."publication_topics" to "service_role";

grant trigger on table "public"."publication_topics" to "service_role";

grant truncate on table "public"."publication_topics" to "service_role";

grant update on table "public"."publication_topics" to "service_role";

grant delete on table "public"."publications" to "anon";

grant insert on table "public"."publications" to "anon";

grant references on table "public"."publications" to "anon";

grant select on table "public"."publications" to "anon";

grant trigger on table "public"."publications" to "anon";

grant truncate on table "public"."publications" to "anon";

grant update on table "public"."publications" to "anon";

grant delete on table "public"."publications" to "authenticated";

grant insert on table "public"."publications" to "authenticated";

grant references on table "public"."publications" to "authenticated";

grant select on table "public"."publications" to "authenticated";

grant trigger on table "public"."publications" to "authenticated";

grant truncate on table "public"."publications" to "authenticated";

grant update on table "public"."publications" to "authenticated";

grant delete on table "public"."publications" to "service_role";

grant insert on table "public"."publications" to "service_role";

grant references on table "public"."publications" to "service_role";

grant select on table "public"."publications" to "service_role";

grant trigger on table "public"."publications" to "service_role";

grant truncate on table "public"."publications" to "service_role";

grant update on table "public"."publications" to "service_role";

grant delete on table "public"."skills" to "anon";

grant insert on table "public"."skills" to "anon";

grant references on table "public"."skills" to "anon";

grant select on table "public"."skills" to "anon";

grant trigger on table "public"."skills" to "anon";

grant truncate on table "public"."skills" to "anon";

grant update on table "public"."skills" to "anon";

grant delete on table "public"."skills" to "authenticated";

grant insert on table "public"."skills" to "authenticated";

grant references on table "public"."skills" to "authenticated";

grant select on table "public"."skills" to "authenticated";

grant trigger on table "public"."skills" to "authenticated";

grant truncate on table "public"."skills" to "authenticated";

grant update on table "public"."skills" to "authenticated";

grant delete on table "public"."skills" to "service_role";

grant insert on table "public"."skills" to "service_role";

grant references on table "public"."skills" to "service_role";

grant select on table "public"."skills" to "service_role";

grant trigger on table "public"."skills" to "service_role";

grant truncate on table "public"."skills" to "service_role";

grant update on table "public"."skills" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";

grant delete on table "public"."user_products" to "anon";

grant insert on table "public"."user_products" to "anon";

grant references on table "public"."user_products" to "anon";

grant select on table "public"."user_products" to "anon";

grant trigger on table "public"."user_products" to "anon";

grant truncate on table "public"."user_products" to "anon";

grant update on table "public"."user_products" to "anon";

grant delete on table "public"."user_products" to "authenticated";

grant insert on table "public"."user_products" to "authenticated";

grant references on table "public"."user_products" to "authenticated";

grant select on table "public"."user_products" to "authenticated";

grant trigger on table "public"."user_products" to "authenticated";

grant truncate on table "public"."user_products" to "authenticated";

grant update on table "public"."user_products" to "authenticated";

grant delete on table "public"."user_products" to "service_role";

grant insert on table "public"."user_products" to "service_role";

grant references on table "public"."user_products" to "service_role";

grant select on table "public"."user_products" to "service_role";

grant trigger on table "public"."user_products" to "service_role";

grant truncate on table "public"."user_products" to "service_role";

grant update on table "public"."user_products" to "service_role";

grant delete on table "public"."user_publications" to "anon";

grant insert on table "public"."user_publications" to "anon";

grant references on table "public"."user_publications" to "anon";

grant select on table "public"."user_publications" to "anon";

grant trigger on table "public"."user_publications" to "anon";

grant truncate on table "public"."user_publications" to "anon";

grant update on table "public"."user_publications" to "anon";

grant delete on table "public"."user_publications" to "authenticated";

grant insert on table "public"."user_publications" to "authenticated";

grant references on table "public"."user_publications" to "authenticated";

grant select on table "public"."user_publications" to "authenticated";

grant trigger on table "public"."user_publications" to "authenticated";

grant truncate on table "public"."user_publications" to "authenticated";

grant update on table "public"."user_publications" to "authenticated";

grant delete on table "public"."user_publications" to "service_role";

grant insert on table "public"."user_publications" to "service_role";

grant references on table "public"."user_publications" to "service_role";

grant select on table "public"."user_publications" to "service_role";

grant trigger on table "public"."user_publications" to "service_role";

grant truncate on table "public"."user_publications" to "service_role";

grant update on table "public"."user_publications" to "service_role";


  create policy "Enable delete for users based on follower_id"
  on "public"."follows"
  as permissive
  for delete
  to public
using ((( SELECT auth.uid() AS uid) = follower_id));



  create policy "Enable read access for all users"
  on "public"."posts"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for users based on user_id"
  on "public"."profile"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = user_id));


  create policy "Enable insert for authenticated users 6idqt3_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'post_images'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



